steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/flask-app:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/flask-app:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - pal-flask-vm
      - --zone=us-central1-a
      - --command
      - |
        docker ps -q | xargs -r docker stop
        docker pull us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/flask-app:$SHORT_SHA
        docker run -d -p 5000:5000 us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/flask-app:$SHORT_SHA
